name: edu_diary
description: "Unofficial edu diary client"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  http: ^1.2.1
  intl: ^0.19.0
  date_format: ^2.0.7
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  email_validator: ^2.1.17
  firebase_core: ^2.31.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/