// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMVTOKcY1l_oft1nyI9CSZHe0PmM-NE7s',
    appId: '1:575101660631:android:419b0032aba2766d45af92',
    messagingSenderId: '575101660631',
    projectId: 'diary-ee752',
    databaseURL: 'https://diary-ee752-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diary-ee752.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBdxnkg1L7p3tzg_vJulQS51os0h98BS4',
    appId: '1:575101660631:ios:5ecc26e4809c4d8845af92',
    messagingSenderId: '575101660631',
    projectId: 'diary-ee752',
    databaseURL: 'https://diary-ee752-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diary-ee752.appspot.com',
    androidClientId: '575101660631-3i71615kcau0b9l1etfsmsr06338iktb.apps.googleusercontent.com',
    iosClientId: '575101660631-vfak7jpf2i15d52jsctk63evtroiom0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduDiary',
  );
}
